version: "3.8"
services:
  postgres:
    container_name: mp_postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: mp_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: marketplace
      PG_DATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

# Alterar para inserir essa configuração no projeto de envio de email
#  mongo:
#    image: mongo:latest
#    container_name: mp_mongodb
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo-data:/data/db

  redis:
    container_name: mp_redis
    image:  redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  mongo-data: