services:
  postgres:
    container_name: mp_postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: mp_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: marketplace
      PG_DATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mp_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    container_name: mp_rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres-data:
  mongo-data: