spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/muvent
    username: user
    password: marketplace
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/myappdb